modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"

[[mods]]
modId = "ktice"
version = "${file.jarVersion}"
displayName = "KubeJS Tinkers Construct Extra"

logoFile="icon.png"
logoBlur=true

authors = "Chemiofitor"

description = '''
Additional TiC compatibility for kubejs.
'''

[[dependencies.ktice]] #optional
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ktice]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ktice]]
modId="tconstruct"
mandatory=true
versionRange="[3.5.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.ktice]]
modId="kubejs"
mandatory=true
versionRange="[1802.5.5-build.562,)"
ordering="NONE"
side="BOTH"
